version: '3.9'

services:
  web:
    container_name: 'ecom_web'
    build: .
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-t*p82+p583sq_zdo9zjhsns5xon*4w847+y*2rcq-j1m!q@)m_"
      - "DJANGO_DEBUG=True"
      - "DJANGO_DATABASE_URL=mysql://username:root@ecom_db:3306/ecom"
      - "DJANGO_GPDR_DATABASE=mysql://username:root@ecom_db:3306/gpdr"
    command: python /www/ecommerce/src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www/ecommerce/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: 'ecom_mysql'
    image: mysql:latest
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - "MYSQL_DATABASE=ecom"
      - "MYSQL_USER=username"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ecom_db:/etc/mysql

volumes:
  ecom_db:
