# Generated by Django 4.1.3 on 2022-12-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'function',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=40, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('picture', models.ImageField(upload_to='', verbose_name='Photo')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.function')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
